### PR TITLE
[tools] Starting the internal RAML side up

### PR DESCRIPTION
**Pull request by nimbinatus**

### CODE REVIEW

**Comment by nimbinatus** [comment]
Just got this one working on Jenkins in full with a test repo. Please review and comment.

**Comment by asettle** [comment]
LGTM - do you want a merge?

**Comment by nimbinatus** [comment]
@asettle, I have tested it, but I'd like it if you all could test it, too. I'll set up something to explain how to test it in a bit. Thanks!

**Comment by nimbinatus** [comment]
Due to switching to IX/GHE, merging

**Pull request merged**
